PATH:=$(PATH):PATH=$PATH:$(HOME)/buildroot-2026.08-rc1/output/host/usr/bin

obj-m += mymmap.o

all:
	echo $(PATH)
	make ARCH=arm CROSS_COMPILE=arm-buildroot-linux-gnueabihf- -C \
$(HOME)/buildroot-2026.08-rc1/output/build/linux-custom M=$(PWD) modules

clean:
	rm *.o *.ko *.mod.c .*.cmd
